### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by jamesevickery** [bmorelli25/interactive-bitcoin-price-chart#3]
Running locally (live demo at https://interactive-bitcoin-price-chart-yenswahhtb.now.sh not loading),

looks perfect in Chrome:

![Chrome](https://user-images.githubusercontent.com/14852491/34331269-334d3c4e-e91d-11e7-8c24-ff7a37a6c4f3.png)

but doesn't display graph path or area in Firefox:

![Firefox](https://user-images.githubusercontent.com/14852491/34331259-1d13420c-e91d-11e7-8d09-338c248b9dbb.png)

Firefox version:

![Firefox version](https://user-images.githubusercontent.com/14852491/34331313-87f505a6-e91d-11e7-98bc-d0d2ac114069.png)

**Comment by bmorelli25** [comment]
Thanks for the heads up on this! Closing per #4

**Comment by jamesevickery** [comment]
Thanks
